### ISSUE TITLE
Running the contributed command:'extension.toggleProxy' fail.

### ISSUE THREAD

**Issue by marekkaczkowski** [satokaz/vscode-toggleProxy#9]
Hey,

- macOS 10.12.6 (16G1311),
- VS Code 1.21.0,
- Toggle Proxy 0.4.4

I'm getting `Running the contributed command:'extension.toggleProxy' fail.` error from `notificationsAlerts.ts`

![screen shot 2018-03-10 at 09 19 28](https://user-images.githubusercontent.com/273831/37239972-56af44b8-2444-11e8-848e-74491b85f878.png)

On the other side looks like Toggle Proxy toggles `http_proxy` in user settings:

![screen shot 2018-03-10 at 09 24 44](https://user-images.githubusercontent.com/273831/37240003-eeaa102c-2444-11e8-9ffb-7c7e89d138b4.png)

**Comment by satokaz** [comment]
@marekkaczkowski Thank you for the report.

I tried it in the following environment: 

* macOS 10.13.2（17C88）
* VS Code 1.21.0 2018-03-07T10:49:32.212Z

But I can not reproduce the problem.

Is something output on Developer Tools (HELP > Toggle Developer Tools ) ?

**Comment by dmaglio** [comment]
same issue for me. VS Code 1.21.0 on Fedora 27 64bit
output from log:
```
[2018-03-26 10:32:35.221] [exthost1] [error] TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at toggleProxy (/home/davidemaglio/.vscode/extensions/satokaz.vscode-toggleproxy-0.4.4/out/src/extension.js:35:32)
    at e._executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:620:380)
    at e.$executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:620:797)
    at e._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:587:832)
    at e._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:587:550)
    at e._receiveRequest (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:586:658)
    at e._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:586:427)
    at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:585:494
    at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:588:343
    at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:87:749
    at e.fire (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:88:992)
    at Socket.<anonymous> (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:143:227)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20) extension.toggleProxy
```
in settings.json i have:
```
"http.proxy": "http://username:password@proxy:port",
"http.proxyStrictSSL": false,
```

**Comment by satokaz** [comment]
@dmaglio Thank you for the report.

Please tell me the directory where `Visual Studio Code.app` is installed.
I seem to be installed in `/usr/share/`, how did you install VS code?

**Comment by dmaglio** [comment]
@satokaz 
```
davidemaglio  ~  whereis code
code: /usr/bin/code /usr/share/code
```

**Comment by satokaz** [comment]
@dmaglio 

> Fedora 27

Sorry, I was misunderstanding.
It was Linux, not macOS.

I will check it in the Linux environment.

**Comment by satokaz** [comment]
#10

**Comment by satokaz** [comment]
@dmaglio 
@marekkaczkowski 

An error occurred when `process.env.TMP` or `process.env.TMPDIR` was undefined.
I released the fixed v0.4.6 in marketplace.

**Comment by dmaglio** [comment]
@satokaz fixed with F27-
Note: the extension comment only `http.proxy` in settings.json, not `http.proxyStrictSSL` or `http.proxyAuthorization`

**Comment by satokaz** [comment]
@dmaglio Thank you for the confirmation.

Do you have problem unless you comment `http.proxyStrictSSL` and `http.proxyAuthorization`?

**Comment by dmaglio** [comment]
@satokaz it isn't a problem, but i think that the extension should comment the row with `http.proxy*` in `settings.json`. IMHO

**Comment by satokaz** [comment]
@dmaglio Thanks for the suggestion. I put it in my Todo as an enhancement request.
